### PR TITLE
Image compression fix for 1003

### PR DESCRIPTION
**Pull request by libertyteeth**
## Description

This "one-line code change" PR fixes compression artifacts in browser screenshots by setting WebP quality to 100%. The issue was particularly noticeable in:

1. Font rendering - especially at smaller sizes (8px)
2. 1px line tests - particularly at angles between 30-45°
3. Gradient tests - showing banding in smooth transitions

### Before/After Comparison
- Before uses the publicly-available 3.0.4
- After changed the version in package.json to 3.0.99 and rebuilt (for a visual indicator; also, to avoid collision with 3.0.5 if released during testing)

#### Font Tests
- Before (3.0.4): Significant blurring and loss of detail in 8px font, with characters appearing fuzzy and sometimes blending together
- After (3.0.99): Crisp text rendering at all sizes, with clear character separation and improved readability

#### Line Tests
- Before (3.0.4): Noticeable aliasing and stair-stepping on angled lines, particularly between 30-45°
- After (3.0.99): Clean, sharp lines at all angles with minimal aliasing and improved edge definition

#### Gradient Tests
- Before (3.0.4): Visible banding in gradients, with distinct steps visible in what should be smooth transitions
- After (3.0.99): Smooth, continuous gradients without banding artifacts

### Technical Details

The fix is to set the WebP quality parameter to 100% in BrowserSession.ts when taking screenshots:

```typescript
let screenshotBase64 = await this.page.screenshot({
    ...options,
    type: "webp",
    quality: 100, // Set maximum quality to prevent compression artifacts
})
```

This ensures maximum quality for WebP compression, eliminating visible artifacts while still maintaining reasonable file sizes through WebP's lossless compression capabilities.

### Testing

Test patterns were created to verify the improvement:
- Font rendering at various sizes (12px, 10px, 8px)
- 1px lines at angles from 0° to 45° in 1° increments
- Gradient patterns to check for banding

Screenshots were captured with both versions and compared to verify the quality improvement. The test files and comparison screenshots are:

Before (3.0.4):
- `3.0.4-2024-12-23T20-43-32-631Z-0a4444.png` - Font tests
- `3.0.4-2024-12-23T20-43-38-736Z-8d061b.png` - Line tests
- `3.0.4-2024-12-23T20-43-44-087Z-3460fb.png` - Gradient tests

After (3.0.99):
- `3.0.99-2024-12-23T20-50-56-414Z-28aa39.png` - Font tests
- `3.0.99-2024-12-23T20-51-03-293Z-1e2c01.png` - Line tests
- `3.0.99-2024-12-23T20-51-17-488Z-77e470.png` - Gradient tests

Comparisons:
- Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below - Screenshot from 2024-12-23 16-14-20.png
- Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, highlights added to identify - Screenshot from 2024-12-23 16-16-34.png

### Note, left is before the fix; right is after it, and appears crystal clear even with max Chroma
- Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, in GIMP, No change - Screenshot from 2024-12-24 12-20-05.png
- Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, in GIMP, Chroma to 100% - Screenshot from 2024-12-24 12-20-59.png

Note: the six Before and After images were saved as .webp files (by adding temporary code to save them, after obtaining them); however, GitHub does not support that type, so I used ImageMagick to convert to .png files.

## Checklist

- [✅] Code follows project style guidelines
- [✅] Documentation has been updated
- [✅] Tests have been added/updated
- [✅] All tests pass
- [✅] Visual regression testing completed with before/after screenshots

## Related Issues

Fixes #1003 - WebP compression artifacts in browser screenshots

3 0 4-2024-12-23T20-43-32-631Z-0a4444
3 0 4-2024-12-23T20-43-38-736Z-8d061b
3 0 4-2024-12-23T20-43-44-087Z-3460fb
3 0 99-2024-12-23T20-50-56-414Z-28aa39
3 0 99-2024-12-23T20-51-03-293Z-1e2c01
3 0 99-2024-12-23T20-51-17-488Z-77e470
Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below - Screenshot from 2024-12-23 16-14-20
Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, highlights added to identify - Screenshot from 2024-12-23 16-16-34
Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, in GIMP, No change - Screenshot from 2024-12-24 12-20-05
Comparison of '42' text in the 42 degree angle, zoomed to 2000%, shows extra pixels above, and changed line color below, in GIMP, Chroma to 100% - Screenshot from 2024-12-24 12-20-59

----

> [!IMPORTANT]
> Fixes image compression artifacts by setting WebP quality to 100% and introduces auto-approval settings and `.clinerules` support.
> 
>   - **Behavior**:
>     - Sets WebP quality to 100% in `BrowserSession.ts` to fix compression artifacts in screenshots.
>     - Introduces auto-approval settings in `AutoApprovalSettings.ts` for actions like reading files, editing files, executing commands, using the browser, and using MCP servers.
>     - Adds `.clinerules` file support for custom project instructions.
>   - **UI Components**:
>     - Adds `AutoApproveMenu.tsx` for managing auto-approval settings in the UI.
>     - Updates `ChatView.tsx` and `ChatRow.tsx` to handle new auto-approval and notification features.
>     - Enhances `BrowserSessionRow.tsx` to reflect changes in browser session handling.
>   - **Misc**:
>     - Updates `ExtensionMessage.ts` and `WebviewMessage.ts` to include new message types for auto-approval and notifications.
>     - Modifies `combineCommandSequences.ts` to handle command approval logic.
>     - Adds system notification support in `notifications/index.ts` for different OS platforms.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Cline&utm_source=github&utm_medium=referral)<sup> for 621692aadb75f5a9a2a6378a1f8e758d52068dc3. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by mrubens** [comment]
This is a great find, thank you! I need to get the repo more in sync with mainline but will figure out how to apply this soon. Thank you for your contribution 🙌

**Comment by libertyteeth** [comment]
This is supposed to be a single line change, but I see I'm merging "55 commits" and the lines changed are "+2,254 −426".

I had wanted to keep the fork/merge history, even though it's small.  I'll make a new PR, and make the change locally.

I got the title wrong too, needed to update that after copying.

**Comment by mrubens** [comment]
Sounds great - let me know when it's ready!

**Comment by libertyteeth** [comment]
> Sounds great - let me know when it's ready!

Thank you.  Asking AIs for assistance with issues clicking around in the UI while attempting to submit this PR, I received, "this is a common complaint with GitHub."  1/2 :)

I see that I missed your earlier comment.  When I saw the "no changeset found", I thought I had made an even worse mistake than bringing 55 changes over, so I bailed out.

Based on your comments, I "think it might be ready now" -- if you're okay with my helping bring those other 54 PRs forward.  The bots see no issues with them.

I am reopening with that in mind, and will await further guidance.

Although, I *did* also see that it would bring over the UI components which Cline recently added -- the checkbox in the chat window for permissions, which differs from the configuration settings you had added, prior to Cline's.

And, a "thinking out of the box" idea: if both settings UIs pull from a common base (which could even include the i18n strings), then maybe providing users with both "belt, AND suspenders" options would fit more pants and other coverings-that-might-not-come-with-belt-loops-to-begin-with?  (To extend a metaphor to the breaking point, perhaps...  :)  My goal is genuine: help as many as possible.)

Thank you again!

**Comment by libertyteeth** [comment]
Again, a wrong click (Commented only); now, the reopen button.  Gives me the opportunity to say, thank you again.

**Comment by libertyteeth** [comment]
> Sounds great - let me know when it's ready!

Thank you again!  I have followed one of the "Plan B" instructions the AIs gave me earlier: clone to someone else, or an organization.  I just happened to have a mostly-unused organization, so was able to do it in short order.  Will close this one, again, so you can merge those other 54 at your leisure.

Now family stuff.  Have a wonderful Christmas Eve!

**Comment by libertyteeth** [comment]
...and, it's gone.  :)

**Pull request closed without merging**
