### PR TITLE
fix: create a merge commit: merge cline:main to RooVetGit:main

### PR DESCRIPTION
**Pull request by lloydchang**
Please choose the standard "create a merge commit" option instead of using the "squash and merge" option
* retry of https://github.com/RooVetGit/Roo-Cline/pull/63#issuecomment-2536490326

----

> [!IMPORTANT]
> Update `README.md` links for feature requests and hiring information.
> 
>   - **README.md Updates**:
>     - Updated "Docs" link to "Feature Requests" with new URL.
>     - Updated "Feature Requests" link to "We're Hiring!" with new URL.
>     - Added careers page link in the "Contributing" section.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Cline&utm_source=github&utm_medium=referral)<sup> for b5d03dd523cd8a802825c724a61853dacf009e2f. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by lloydchang** [comment]
> Some checks haven’t completed yet
> 4 successful and 1 expected checks

> compile Expected — Waiting for status to be reported
> Required

i don't why github actions is stuck at "expected" and "waiting"

**Comment by lloydchang** [comment]
> > Some checks haven’t completed yet
> > 4 successful and 1 expected checks
> 
> > compile Expected — Waiting for status to be reported
> > Required
> 
> i don't why github actions is stuck at "expected" and "waiting"

update:

compile reported now (23 minutes after pull request creation)

**Comment by ColemanRoo** [comment]
> > Some checks haven’t completed yet
> > 4 successful and 1 expected checks
> 
> > compile Expected — Waiting for status to be reported
> > Required
> 
> i don't why github actions is stuck at "expected" and "waiting"

I was making some changes to merge rulesets in prep of some other changes coming soon; I'll remove for now until we get those changes merged.

**Comment by lloydchang** [comment]
> I was making some changes to merge rulesets in prep of some other changes coming soon; I'll remove for now until we get those changes merged.

ok

—

update:

compile reported now (23 minutes after pull request creation)

—

i don't know if it's because of your changes in progress, or it eventually finished after 23 minutes

**Review by mrubens — APPROVED** [review]

**Comment by lloydchang** [comment]
lgtm

**Comment by lloydchang** [comment]
> lgtm

this pull request merged as expected

https://github.com/RooVetGit/Roo-Cline/compare/main...cline:cline:main

says

> There isn’t anything to compare.
> `RooVetGit:main` is up to date with all commits from `cline:main`. 

and https://github.com/RooVetGit/Roo-Cline/

says

> This branch is [106 commits ahead of](https://github.com/RooVetGit/Roo-Cline/compare/cline%3Acline%3Amain...main) cline/cline:main.

**Pull request merged**
