### PR TITLE
Improved regex for auto-execution of chained commands

### PR DESCRIPTION
**Pull request by stea9499**
## Description
Improved regex for auto-execution of chained commands. Addresses issue https://github.com/RooVetGit/Roo-Cline/issues/156 - thanks to @deathtothenig for providing the fix.

The key difference between the regex patterns is how they handle pipe characters:

1. Original regex: /&&|\|\||;|\||\$\(|/`
    - Matches ALL pipe characters regardless of context
    - Would incorrectly split commands like echo "hello | world"
2. Updated regex: /&&|\|\||;|(?<!"[^"]*)\|(?![^"]*")|\$\(|/`
    - Uses lookaround assertions to only match pipes outside of quotes
    - Preserves quoted strings containing pipes as single commands

Example behaviors:
```
echo "hello | world"       // Original: Splits on |
                           // Updated: Keeps as one command (pipe ignored)

npm test | grep error      // Both: Split on | (pipe is operator)

command "arg1" | grep      // Both: Split on | (pipe is operator)

echo 'text | more' | grep  // Original: Splits into 3 parts
                           // Updated: Splits into 2 parts (respects quotes)
```

The tests added verify this behavior by including:
1. Commands with quoted pipes that should be treated as literal characters
2. Commands with unquoted pipes that should be treated as operators
3. Complex PowerShell pipelines that mix both quoted and unquoted pipes
This ensures the regex correctly distinguishes between pipes used as command operators and pipes that are part of quoted command arguments.

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Unit tests + manual tested locally

## Checklist:
- [X] My code follows the patterns of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

## Additional context
N/A

## Related Issues
https://github.com/RooVetGit/Roo-Cline/issues/156

## Reviewers
@mrubens @ColemanRoo 

----

> [!IMPORTANT]
> Improves regex in `ChatView.tsx` to correctly handle pipes within quotes and updates tests in `ChatView.test.tsx` to verify command parsing behavior.
> 
>   - **Behavior**:
>     - Updated regex in `ChatView.tsx` to split commands using `/&&|\|\||;|(?<!"[^"]*)\|(?![^"]*")|\$\(|`/` to handle pipes within quotes correctly.
>     - Ensures commands like `echo "hello | world"` are treated as single commands.
>   - **Tests**:
>     - Added tests in `ChatView.test.tsx` for commands with quoted pipes to ensure they are not split.
>     - Verified behavior for both allowed and disallowed command chains, including complex PowerShell commands.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Cline&utm_source=github&utm_medium=referral)<sup> for 556e25f74fa72618e095e72068137da7334ca908. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by mrubens — APPROVED** [review]
Are changesets working now?

Code looks good.

**Comment by stea9499** [comment]
> Are changesets working now?
> 
> Code looks good.

I'm out of the loop on the state of changesets and the release process now. @ColemanRoo can you advise here, and is this good to go in it's current form?

**Comment by ColemanRoo** [comment]
> > Are changesets working now?
> > Code looks good.
> 
> I'm out of the loop on the state of changesets and the release process now. @ColemanRoo can you advise here, and is this good to go in it's current form?

It looks good to me; let merge it; I know @a8trejo made some changes to the flows and settings recently so this should work.  If it doesn't I can manually publish from `main`

**Review by ColemanRoo — APPROVED** [review]

**Comment by a8trejo** [comment]
let's add a `changeset`, it should work, if not i'll jump in to check

**Comment by a8trejo** [comment]
> let's add a `changeset`, it should work, if not i'll jump in to check

there's some repo setting that needs to be enabled for it to work but I don't have access to it
image

**Pull request merged**
